const SHOES = [
	{
		slug: "tech-challenge",
		name: "NikeCourt Tech Challenge 20",
		imageSrc: [
			"/tech-challenge-1.jpg",
			"/tech-challenge-2.jpeg",
			"/tech-challenge-3.jpeg",
			"/tech-challenge-4.jpeg",
		],
		price: 16500,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 1,
		numOfColors: 2,
		thumbnails: [
			"/tech-challenge-1-thumbnail.jpg",
			"/tech-challenge-2-thumbnail.jpeg",
			"/tech-challenge-3-thumbnail.jpeg",
			"/tech-challenge-4-thumbnail.jpeg",
		],
	},
	{
		slug: "metcon-5",
		name: "Nike Metcon 5 AMP",
		imageSrc: "/metcon-5.jpg",
		price: 16500,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 2,
		numOfColors: 1,
	},
	{
		slug: "phantom",
		name: "Nike Phantom Vision",
		imageSrc: "/phantom.jpg",
		price: 16500,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 4,
		numOfColors: 4,
	},
	{
		slug: "pegasus",
		name: "Nike Air Zoom Pegasus",
		imageSrc: "/pegasus.jpg",
		price: 16500,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 16,
		numOfColors: 1,
	},
	{
		slug: "joyride",
		name: "Nike Joyride Dual Run",
		imageSrc: "/joyride.jpg",
		price: 17000,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 40,
		numOfColors: 2,
	},
	{
		slug: "legend-academy",
		name: "Nike Tiempo Legend 8",
		imageSrc: "/legend-academy.jpg",
		price: 16500,
		salePrice: 12500,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 50,
		numOfColors: 8,
	},
	{
		slug: "react-infinity",
		name: "Nike React Infinity Pro",
		imageSrc: "/react-infinity.jpg",
		price: 16000,
		salePrice: 14500,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 75,
		numOfColors: 1,
	},
	{
		slug: "phantom-flyknit",
		name: "Nike React Phantom Run Flyknit 2",
		imageSrc: "/phantom-flyknit.jpg",
		price: 18500,
		salePrice: 16000,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 100,
		numOfColors: 4,
	},
	{
		slug: "lebron",
		name: "LeBron 17",
		imageSrc: "/lebron.jpg",
		price: 26000,
		salePrice: null,
		releaseDate: Date.now() - 1000 * 60 * 60 * 24 * 120,
		numOfColors: 1,
	},
];

export default SHOES;
